#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndroidParseTestApp.Resource", IsApplication=true)]

namespace AndroidParseTestApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int day_array = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int endTimeArray = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int startTimeArray = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int button1 = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int day_prompt = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int edittext = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int end_time = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int listView1 = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int start_time = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int textView2 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int textView3 = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int textView4 = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int List = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int day_prompt = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int end_time = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int start_time = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
